### ISSUE TITLE
xml submission on plugins.glpi-project.org

### ISSUE THREAD

**Issue by orthagh** [NiledaFR/pluginsGLPI-certificateticket#1]
I received your request to be present in the plugins catalog.
could you please fix the following issue in your XML file:

- https://github.com/NiledaFR/pluginsGLPI-certificateticket/blob/main/certificateticket.xml#L13-L16 <- Could you fill some url here, so people will find how to retrieve your plugin
- could you create a tag/release on your GitHub repository to ease the installation on a GLPI ?

Regards

**Comment by NiledaFR** [comment]
Hi,
I filled the URL and created a release tag
Regards

**Comment by orthagh** [comment]
Thx ! I published the plugin, it should be live in 1h or so
